### ISSUE TITLE
subcurrency.cll wont compile

### ISSUE THREAD

**Issue by hughht5** [jorisbontje/cll-sim#4]
- python cllcompiler.py subcurrency.cll 

Traceback (most recent call last):
  File "cllcompiler.py", line 208, in <module>
    print ' '.join([str(k) for k in compile(open(sys.argv[1]).read())])
  File "cllcompiler.py", line 201, in compile
    p = parse_lines(lines)
  File "/Users/hhalfordthompson/ethereum/compiler/cllparser.py", line 38, in parse_lines
    out.append(parse_lines(child_block))
  File "/Users/hhalfordthompson/ethereum/compiler/cllparser.py", line 32, in parse_lines
    out = parse_line(main)
  File "/Users/hhalfordthompson/ethereum/compiler/cllparser.py", line 217, in parse_line
    return [ 'set', shunting_yard(tokens[:eqplace]), shunting_yard(tokens[eqplace+1:]) ]
  File "/Users/hhalfordthompson/ethereum/compiler/cllparser.py", line 162, in shunting_yard
    typ = toktype(tok)
  File "/Users/hhalfordthompson/ethereum/compiler/cllparser.py", line 126, in toktype
    else: raise Exception("Invalid token: "+token)
Exception: Invalid token: MYCREATOR

**Comment by jorisbontje** [comment]
`MYCREATOR` is a constant, you need to replace it with your address before compiling.

https://github.com/ethereum/wiki/wiki/%5BEnglish%5D-White-Paper#wiki-applications

```
All variables expressed as capital letters (eg. A) are constants, to be replaced by actual
values by the contract creator when actually releasing the contract.
```
